# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb0426decb58f5051b9d97c517bfe3aa8d453de711ea6d16b87bc11a0e2335bb00924433b17d75336e18e12d2a9be4b74caa5b408be966cad3acb566a165ad1
  google_client_id: "1094414539537-mhmbrrh9vqh6vo8mlr9uksebksc1nq70.apps.googleusercontent.com"
  google_secret: "9MYAXlAVjjnpqq5Qz27zT-Fe"

test:
  secret_key_base: 50f3019c847d26675d2866722499de60eb1202803edfbfa2420b0c6c84aa8ff6e1e99c5138cc5fc6ff8574ac18d50e2d3eb66978c9ea5b5d7b67e727a3ee2324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
