User.create!([
  {id: 4, email: "jack.newton@clio.com", full_name: "Jack Newton", title: "CEO and Founder", manager_id: nil, department_id: 1},
  {id: 5, email: "rian.gauvreau@clio.com", full_name: "Rian Gauvreau", title: "COO and Founder", manager_id: 4, department_id: 1},
  {id: 7, email: "kazia.biernacki@clio.com", full_name: "Kazia Formosa", title: "Switch Specialist", manager_id: 247, department_id: 22},
  {id: 9, email: "kimberly.davison@clio.com", full_name: "Kimberly Davison", title: "Switch Specialist", manager_id: 15, department_id: 22},
  {id: 10, email: "catherine.hillier@clio.com", full_name: "Catherine Hillier", title: "Director of Customer Support", manager_id: 5, department_id: 6},
  {id: 15, email: "jason.pinch@clio.com", full_name: "Jason Pinch", title: "Migrations Manager", manager_id: 247, department_id: 22},
  {id: 16, email: "angus.wong@clio.com", full_name: "Angus Wong", title: "IT Coordinator", manager_id: 5, department_id: 16},
  {id: 19, email: "oliver.browes@clio.com", full_name: "Oliver Browes", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 22, email: "tyler.goodwin@goclio.com", full_name: "Tyler Goodwin", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 33, email: "derek.rawlings@clio.com", full_name: "Derek Rawlings", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 36, email: "joshua.tanzola@clio.com", full_name: "Joshua Tanzola", title: "Director of Sales Engineering", manager_id: 113, department_id: 2},
  {id: 38, email: "dan.woods@clio.com", full_name: "Daniel Woods", title: "Regional Sales Director", manager_id: 113, department_id: 2},
  {id: 39, email: "tonia.chambers@clio.com", full_name: "Antonia Newton", title: "Office Manager", manager_id: 5, department_id: 16},
  {id: 40, email: "remi.broemeling@clio.com", full_name: "Remi Broemeling", title: "System Administrator", manager_id: 4, department_id: 19},
  {id: 42, email: "naoya.makino@clio.com", full_name: "Naoya Makino", title: "Lead Developer - Android", manager_id: 180, department_id: 19},
  {id: 43, email: "fraser.newton@clio.com", full_name: "Fraser Newton", title: "Lead Scientist", manager_id: 46, department_id: 20},
  {id: 44, email: "chris.thompson@clio.com", full_name: "Chris Thompson", title: "Security Lead", manager_id: 45, department_id: 19},
  {id: 45, email: "tys.von.gaza@clio.com", full_name: "Tys von Gaza", title: "Director of Product Development", manager_id: 4, department_id: 19},
  {id: 46, email: "george.psiharis@clio.com", full_name: "George Psiharis", title: "Vice President, Business Development & Partnerships", manager_id: 4, department_id: 20},
  {id: 49, email: "jo.goodrich@clio.com", full_name: "Jo Goodrich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 55, email: "kieran.elliott@clio.com", full_name: "Kieran Elliott", title: "Sr. Software Developer", manager_id: 87, department_id: 19},
  {id: 68, email: "kyle.doliveira@clio.com", full_name: "Kyle d'Oliveira", title: "Software Architecture Specialist", manager_id: 45, department_id: 19},
  {id: 69, email: "geoff.thierman@clio.com", full_name: "Geoffrey Thierman", title: "Sr UI Designer", manager_id: 264, department_id: 19},
  {id: 75, email: "shirley.ho@clio.com", full_name: "Shirley Ho", title: "Sr UI Designer", manager_id: 264, department_id: 19},
  {id: 77, email: "lyndsi.nolan@clio.com", full_name: "Lyndsi Nolan", title: "Customer Support Specialist", manager_id: 10, department_id: 6},
  {id: 78, email: "zachary.pope@clio.com", full_name: "Zachary Pope", title: "Technical Escalations Manager", manager_id: 10, department_id: 6},
  {id: 79, email: "joshua.lenon@clio.com", full_name: "Joshua Lenon", title: "Lawyer in Residence", manager_id: 205, department_id: 8},
  {id: 83, email: "kevin.needham@clio.com", full_name: "Kevin Needham", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 84, email: "eugene.or@clio.com", full_name: "Eugene Or", title: "UI Designer", manager_id: 264, department_id: 19},
  {id: 85, email: "lauren.sanders@clio.com", full_name: "Lauren Sanders", title: "Special Projects Coordinator & Executive Assistant", manager_id: 4, department_id: 18},
  {id: 87, email: "jason.peebles@clio.com", full_name: "Jason Peebles", title: "Lead Developer - iOS", manager_id: 45, department_id: 19},
  {id: 89, email: "dennis.taylor@clio.com", full_name: "Dennis Taylor", title: "Performance Specialist", manager_id: 45, department_id: 19},
  {id: 94, email: "jodelene.weir@clio.com", full_name: "Jodelene Weir", title: "Event Producer", manager_id: 46, department_id: 8},
  {id: 95, email: "craig.carlyle@clio.com", full_name: "Craig Carlyle", title: "UI Designer", manager_id: 141, department_id: 19},
  {id: 97, email: "kyle.demeule@clio.com", full_name: "Kyle Demeule", title: "Data Scientist", manager_id: 43, department_id: 20},
  {id: 101, email: "arthur.chui@clio.com", full_name: "Arthur Chui", title: "Senior Software Developer", manager_id: 45, department_id: 19},
  {id: 102, email: "derek.bolen@clio.com", full_name: "Derek Bolen", title: "Social Media & Community Coordinator", manager_id: 127, department_id: 8},
  {id: 104, email: "tanyia.mackenzie@clio.com", full_name: "Tanyia MacKenzie", title: "Office Administrator", manager_id: 39, department_id: 16},
  {id: 107, email: "reilly.forshaw@clio.com", full_name: "Reilly Forshaw", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 109, email: "dana.stasyk@clio.com", full_name: "Dana Stasyk", title: "Customer Support Coordinator", manager_id: 130, department_id: 6},
  {id: 113, email: "steven.silberbach@clio.com", full_name: "Steven Silberbach", title: "Vice President, Global Sales", manager_id: 4, department_id: 2},
  {id: 114, email: "drew.goddyn@clio.com", full_name: "Drew Goddyn", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 115, email: "matthew.horne@goclio.com", full_name: "Matt Horne", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 116, email: "pouyan.bibalan@clio.com", full_name: "Pouyan Taghipour Bibalan", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 117, email: "jeremy.papp@clio.com", full_name: "Jeremy Papp", title: "Product Team Project Manager", manager_id: 45, department_id: 19},
  {id: 121, email: "rory.fitzpatrick@clio.com", full_name: "Rory Fitzpatrick", title: "Customer Success Coordinator", manager_id: 166, department_id: 22},
  {id: 123, email: "navneet.gill@clio.com", full_name: "Navneet Gill", title: "Data Operations Analyst", manager_id: 46, department_id: 20},
  {id: 124, email: "adrian.pape@clio.com", full_name: "Adrian Pape", title: "Controller", manager_id: 172, department_id: 9},
  {id: 125, email: "halley.strecko@clio.com", full_name: "Halley Strecko", title: "Customer Success Associate", manager_id: 247, department_id: 22},
  {id: 126, email: "christopher.yeh@clio.com", full_name: "Christopher Yeh", title: "Manager of Talent Development", manager_id: 5, department_id: 16},
  {id: 127, email: "preet.minhas@clio.com", full_name: "Preet Minhas", title: "Director of Inbound Marketing and Operations", manager_id: 4, department_id: 8},
  {id: 129, email: "brendan.devereux@clio.com", full_name: "Brendan Devereux", title: "Switch Specialist", manager_id: 15, department_id: 22},
  {id: 130, email: "david.perry@clio.com", full_name: "David Perry", title: "Customer Support Manager", manager_id: 10, department_id: 6},
  {id: 131, email: "jon.tastemel@clio.com", full_name: "Jon Tastemel", title: "Web Developer", manager_id: 127, department_id: 8},
  {id: 132, email: "elsa.brink@clio.com", full_name: "Elsa Brink", title: "Senior Demand Generation Marketing Manager", manager_id: 4, department_id: 8},
  {id: 133, email: "lynn.gagne@clio.com", full_name: "Lynn Gagne", title: "Customer Success Trainer", manager_id: 247, department_id: 22},
  {id: 134, email: "chelsea.kelch@clio.com", full_name: "Chelsea Kelch", title: "Customer Success Coordinator", manager_id: 247, department_id: 22},
  {id: 135, email: "catherine.mclachlan@clio.com", full_name: "Catherine McLachlan", title: "Designer", manager_id: 136, department_id: 8},
  {id: 136, email: "jiaan.co@clio.com", full_name: "Jiaan Co", title: "Visual Designer", manager_id: 127, department_id: 8},
  {id: 137, email: "daniela.szary@clio.com", full_name: "Daniela Szary", title: "Event Planner", manager_id: 4, department_id: 8},
  {id: 138, email: "kyle.harrison@clio.com", full_name: "Kyle Harrison", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 139, email: "jeremy.secker@clio.com", full_name: "Jeremy Secker", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 141, email: "terry.white@clio.com", full_name: "Terry White", title: "Software Developer", manager_id: 45, department_id: 19},
  {id: 142, email: "muriel.teague@clio.com", full_name: "Muriel Teague", title: "Customer Success Trainer", manager_id: 130, department_id: 22},
  {id: 143, email: "adam.stanton@clio.com", full_name: "Adam Stanton", title: "System Administrator", manager_id: 40, department_id: 19},
  {id: 144, email: "ryan.sydor@clio.com", full_name: "Ryan Sydor", title: "Regional Sales Director", manager_id: 113, department_id: 2},
  {id: 145, email: "jordan.suen@clio.com", full_name: "Jordan Suen", title: "Senior Accountant", manager_id: 124, department_id: 9},
  {id: 147, email: "colin.mcmahon@clio.com", full_name: "Colin McMahon", title: "Training Specialist", manager_id: 10, department_id: 6},
  {id: 152, email: "yuki.hamade@clio.com", full_name: "Yuki Hamade", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 153, email: "john.oconnor@clio.com", full_name: "John O'Connor", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 154, email: "melanie.watson@clio.com", full_name: "Melanie Watson", title: "Senior Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 156, email: "hamad.mirza@clio.com", full_name: "Hamad Mirza", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 157, email: "maggie.nyunt@clio.com", full_name: "Margaret Peckham-Nyunt", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 160, email: "carina.hunt@clio.com", full_name: "Carina Dielissen Hunt", title: "Training Specialist (New Releases)", manager_id: 10, department_id: 6},
  {id: 163, email: "marc.barlo@clio.com", full_name: "Marc Barlo", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 164, email: "kaitlin.graves@clio.com", full_name: "Kaitlin Graves", title: "Office Administrator", manager_id: 39, department_id: 16},
  {id: 165, email: "leslie.sto.tomas@clio.com", full_name: "Leslie Sto. tomas", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 166, email: "derek.fitzpatrick@clio.com", full_name: "Derek Fitzpatrick", title: "General Manager, EMEA", manager_id: 46, department_id: 11},
  {id: 167, email: "saad.ahmed@clio.com", full_name: "Saad Ahmed", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 169, email: "brittany.holmes@clio.com", full_name: "Brittany Holmes", title: "Switch Specialist", manager_id: 247, department_id: 22},
  {id: 170, email: "mark.rainey@clio.com", full_name: "Mark Rainey", title: "Customer Support Coordinator", manager_id: 130, department_id: 6},
  {id: 171, email: "sean.healy@clio.com", full_name: "Sean Healy", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 172, email: "robert.froment@clio.com", full_name: "Rob Froment", title: "Chief Financial Officer", manager_id: 4, department_id: 9},
  {id: 173, email: "sherry.shao@clio.com", full_name: "Sherry Shao", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 176, email: "richard.chong@clio.com", full_name: "Richard Chong", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 179, email: "prashant.jacob@clio.com", full_name: "Prashant Jacob", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 180, email: "jordan.raine@clio.com", full_name: "Jordan Raine", title: "Software Developer", manager_id: 45, department_id: 19},
  {id: 181, email: "michael.cheung@clio.com", full_name: "Michael Cheung", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 183, email: "nicholas.paufler@clio.com", full_name: "Nicholas Paufler", title: "System Administrator", manager_id: 40, department_id: 19},
  {id: 188, email: "brittney.lloyd@clio.com", full_name: "Brittney Lloyd", title: "Business Development Administrator", manager_id: 195, department_id: 11},
  {id: 189, email: "walt.nathaniel@clio.com", full_name: "Walt Nathaniel", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 190, email: "dylan.runkel@clio.com", full_name: "Dylan Runkel", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 191, email: "michelle.fryzuk@clio.com", full_name: "Michelle Fryzuk", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 192, email: "brian.oreilly@clio.com", full_name: "Brian O'Reilly", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 193, email: "pavel.dusatko@clio.com", full_name: "Pavel Dusatko", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 194, email: "luke.wagner@clio.com", full_name: "Luke Wagner", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 195, email: "andrew.gay@clio.com", full_name: "Andrew Gay", title: "Manager of Strategic Partnerships", manager_id: 46, department_id: 11},
  {id: 199, email: "matthew.faust@clio.com", full_name: "Matthew Faust", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 201, email: "michael.wei@clio.com", full_name: "Mike Wei", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 202, email: "audrey.gagnon@clio.com", full_name: "Audrey Gagnon", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 203, email: "eric.bin@clio.com", full_name: "Eric Bin", title: "Lead Product Manager", manager_id: 4, department_id: 19},
  {id: 204, email: "aaron.cheng@clio.com", full_name: "Aaron Cheng", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 205, email: "beth.kszan@clio.com", full_name: "Beth Kszan", title: "Director, Product Marketing", manager_id: 4, department_id: 8},
  {id: 206, email: "taryn.friederich@clio.com", full_name: "Taryn Friederich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 207, email: "tyler.nelson@clio.com", full_name: "Tyler Nelson", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 208, email: "andrea.stevenson@clio.com", full_name: "Andrea Stevenson", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 209, email: "jef.curtis@clio.com", full_name: "Jef Curtis", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 210, email: "ilana.shulman@clio.com", full_name: "Ilana Shulman", title: "Director of Business Development", manager_id: 113, department_id: 2},
  {id: 211, email: "tami.runyon@clio.com", full_name: "Tami Runyon", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 212, email: "jane.lee@clio.com", full_name: "Jane Lee", title: "Talent Acquisition Specialist", manager_id: 126, department_id: 16},
  {id: 213, email: "darren.wilson@clio.com", full_name: "Darren Wilson", title: "Copywriter", manager_id: 127, department_id: 8},
  {id: 214, email: "erick.costigan@clio.com", full_name: "Erick Costigan", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 215, email: "erik.auvinen@clio.com", full_name: "Erik Auvinen", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 216, email: "alex.kim@clio.com", full_name: "Alex Kim", title: "Talent Acquisition Specialist", manager_id: 126, department_id: 16},
  {id: 217, email: "waylon.mcgill@clio.com", full_name: "Waylon McGill", title: "Manager, Sales Development", manager_id: 113, department_id: 2},
  {id: 218, email: "josh.lecker@clio.com", full_name: "Josh Lecker", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 222, email: "marcus.stein@clio.com", full_name: "Marcus Stein", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 223, email: "ashique.khan@clio.com", full_name: "Ashique Khan", title: "Manager, Sales Operations", manager_id: 46, department_id: 20},
  {id: 224, email: "guillermo.tellez@clio.com", full_name: "Guillermo Tellez", title: "Senior Product Manager", manager_id: 203, department_id: 19},
  {id: 226, email: "amy.berkowitz@clio.com", full_name: "Amy Berkowitz", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 228, email: "wade.fraser@clio.com", full_name: "Wade Fraser", title: "Senior Business Development Representative", manager_id: 210, department_id: 2},
  {id: 229, email: "georgina.marcus@clio.com", full_name: "Georgina Marcus", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 231, email: "matthew.patterson@clio.com", full_name: "Matthew Patterson", title: "Senior Business Development Representative", manager_id: 210, department_id: 2},
  {id: 233, email: "mark.reich@clio.com", full_name: "Mark Reich", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 234, email: "emmanuel.akena@clio.com", full_name: "Emmanuel Akena", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 235, email: "michelle.lodge@clio.com", full_name: "Michelle Lodge", title: "Payroll & Benefits Coordinator", manager_id: 124, department_id: 9},
  {id: 237, email: "steven.harbaruk@clio.com", full_name: "Steven Harbaruk", title: "Intern, Product Management", manager_id: 203, department_id: 19},
  {id: 239, email: "paul.holden@clio.com", full_name: "Paul Holden", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 240, email: "fiona.finn@clio.com", full_name: "Fiona Finn", title: "Marketing Specialist", manager_id: 205, department_id: 8},
  {id: 243, email: "roshini.sakhrani@clio.com", full_name: "Roshini Sakhrani", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 244, email: "jeff.marvin@clio.com", full_name: "Jeff Marvin", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 245, email: "dwight.tomalty@clio.com", full_name: "Dwight Tomalty", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 246, email: "charles.ferguson@clio.com", full_name: "Charles Ferguson", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 247, email: "michael.chou@clio.com", full_name: "Michael Chou", title: "Customer Success Manager", manager_id: 5, department_id: 22},
  {id: 248, email: "jason.cho@clio.com", full_name: "Jason Cho", title: "Quality Assurance Analyst ", manager_id: 291, department_id: 19},
  {id: 249, email: "ryan.akerboom@clio.com", full_name: "Ryan Akerboom", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 251, email: "nathaniel.mots@clio.com", full_name: "Nathaniel Mots", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 253, email: "rebecca.mcmanus@clio.com", full_name: "Rebecca McManus", title: "Sales Development Rep", manager_id: 166, department_id: 13},
  {id: 254, email: "ross.weldon@clio.com", full_name: "Ross Weldon", title: "Marketing Specialist", manager_id: 166, department_id: 8},
  {id: 255, email: "aiza.corcuera@clio.com", full_name: "Aiza Corcuera", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 256, email: "ruman.kang@clio.com", full_name: "Ruman Kang", title: "Content Marketing Specialist", manager_id: 127, department_id: 8},
  {id: 257, email: "jeffrey.huang@clio.com", full_name: "Jeffrey Huang", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 258, email: "james.goertzen@clio.com", full_name: "James Goertzen", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 259, email: "adam.dewji@clio.com", full_name: "Adam Dewji", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 260, email: "jonathan.ho@clio.com", full_name: "Jonathan Ho", title: "Marketing Operations Specialist", manager_id: 127, department_id: 8},
  {id: 261, email: "rehan.nayyer@clio.com", full_name: "Rehan Nayyer", title: "Salesforce Developer", manager_id: 46, department_id: 20},
  {id: 263, email: "alexander.kardash@clio.com", full_name: "Alexander Kardash", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 264, email: "ernie.bin@clio.com", full_name: "Ernie Bin", title: "Director, User Experience", manager_id: 4, department_id: 19},
  {id: 265, email: "joash.carey@clio.com", full_name: "Joash Carey", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 266, email: "robyn.dobson@clio.com", full_name: "Robyn Dobson", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 267, email: "madison.goddyn@clio.com", full_name: "Madison Goddyn", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 269, email: "cale.shapera@clio.com", full_name: "Cale Shapera", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 270, email: "mengxi.liao@clio.com", full_name: "Mengxi Liao", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 271, email: "jack.chao@clio.com", full_name: "Jack Chao", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 272, email: "david.le.corre@clio.com", full_name: "David Le Corre", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 273, email: "scott.hamilton@clio.com", full_name: "Scott Hamilton", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 275, email: "jeremy.noonan@clio.com", full_name: "Jeremy Noonan", title: "IT Administrator", manager_id: 5, department_id: 16},
  {id: 276, email: "jeff.perrin@clio.com", full_name: "Jeff Perrin", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 277, email: "mark.hazlett@clio.com", full_name: "Mark Hazlett", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 278, email: "kenneth.calcitas@clio.com", full_name: "Kenneth Calcitas", title: "Digital Media Portfolio Specialist", manager_id: 132, department_id: 8},
  {id: 279, email: "irina.belova@clio.com", full_name: "Irina Belova", title: "Senior Product Designer", manager_id: 264, department_id: 19},
  {id: 281, email: "shawky.hanana@clio.com", full_name: "Shawky Hanana", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 282, email: "calvin.cestari@clio.com", full_name: "Calvin Cestari", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 283, email: "jessie.mok@clio.com", full_name: "Jessie Mok", title: nil, manager_id: 124, department_id: 9},
  {id: 284, email: "euphemia.wong@clio.com", full_name: "Euphemia Wong", title: "UX Designer", manager_id: 264, department_id: 19},
  {id: 285, email: "steve.thompson@clio.com", full_name: "Steve Thompson", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 286, email: "michael.brewer@clio.com", full_name: "Michael Brewer", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 287, email: "nelson.wang@clio.com", full_name: "Nelson Wang", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 288, email: "shaheer.shabbir@clio.com", full_name: "Shaheer Shabbir", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 289, email: "irmantas.levanas@clio.com", full_name: "Irmantas Levanas", title: "Account Executive", manager_id: 166, department_id: 2},
  {id: 290, email: "matthew.griffeth@clio.com", full_name: "Matthew Griffeth", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 291, email: "james.coles-nash@clio.com", full_name: "James Coles-Nash", title: "QA Automation Lead", manager_id: 45, department_id: 19},
  {id: 292, email: "jacob.bosancich@clio.com", full_name: "Jacob Bosancich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 293, email: "samantha.sterzai@clio.com", full_name: "Samantha Sterzai", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 295, email: "pawan.kumar.adda@clio.com", full_name: "Pawan Kumar Adda", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 296, email: "agnes.carissa.utomo@clio.com", full_name: "Agnes Utomo", title: "Software Developer, Co-op", manager_id: 101, department_id: 19},
  {id: 297, email: "landon.trybuch@clio.com", full_name: "Landon Trybuch", title: "Software Developer, Co-op", manager_id: 101, department_id: 19},
  {id: 298, email: "karina.simard@clio.com", full_name: "Karina Simard", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 299, email: "andrew.booth@clio.com", full_name: "Andrew Booth", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 300, email: "niamh.monahan@clio.com", full_name: "Niamh Monahan", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 301, email: "katrina.guyduy@clio.com", full_name: "Katrina Guyduy", title: "Web Developer", manager_id: 131, department_id: 8},
  {id: 302, email: "nicole.manalac@clio.com", full_name: "Nicole Manalac", title: "Talent Generalist", manager_id: 126, department_id: 16},
  {id: 303, email: "lydia.choi@clio.com", full_name: "Lydia Choi", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 304, email: "allison.mcgerrigle@clio.com", full_name: "Allison McGerrigle", title: "Talent Generalist", manager_id: 126, department_id: 16}
])
Competency.create!([
  {id: 1, category: "Live a learning Mindset", name: "Strives to understand Product functionality", rank: 0},
  {id: 2, category: "Live a learning Mindset", name: "Strives to understand Customer work flows.", rank: 0},
  {id: 3, category: "Live a learning Mindset", name: "Participates in test plan reviews.", rank: 0},
  {id: 4, category: "Live a learning Mindset", name: "Learns and builds on feedback.", rank: 0},
  {id: 5, category: "Live a learning Mindset", name: "Voice my opinions when I disagree with positions of others", rank: 0},
  {id: 6, category: "Live a learning Mindset", name: "Give my input during the planning phase of features/tickets", rank: 0},
  {id: 7, category: "Live a learning Mindset", name: "Read and Engage in architectural reviews of problems I am familiar with", rank: 0},
  {id: 8, category: "Drawing the Fucking Owl", name: "Own well defined small projects and features to completion with guidance", rank: 0},
  {id: 9, category: "Drawing the Fucking Owl", name: "Prioritize tasks; avoid getting caught up in unimportant details", rank: 0},
  {id: 10, category: "Drawing the Fucking Owl", name: "Make steady progress on tasks - can describe the problem, attempt solutions and knows when to ask for help", rank: 0},
  {id: 11, category: "Drawing the Fucking Owl", name: "Be a vocal advocate for QA/Quality.", rank: 0},
  {id: 12, category: "Technical", name: "Write a DB migration", rank: 0},
  {id: 13, category: "Technical", name: "Create a CoreData migration and understand how it alters the underlying database store", rank: 0},
  {id: 14, category: "Technical", name: "Write code the functions properly and can refactor", rank: 0},
  {id: 15, category: "Technical", name: "Understand core programming concepts", rank: 0},
  {id: 16, category: "Technical", name: "Write/Maintain automated tests and test plans", rank: 0},
  {id: 17, category: "Technical", name: "Understand our frontend frameworks. In particular Angular / Karma / SASS", rank: 0},
  {id: 18, category: "Technical", name: "Understand our backend frameworks. In particular, Rails.", rank: 0},
  {id: 19, category: "Technical", name: "Understand Android APIs and common use (Activity/Fragment lifecycle and other foundational Android framework knowledge)", rank: 0},
  {id: 20, category: "Technical", name: "Strong familiarity with Apple's iOS frameworks, in particular Foundation, UIKit, and CoreData.", rank: 0},
  {id: 21, category: "Clio", name: "Estimate the amout of work required for a ticket in areas of the code base that I am familiar with", rank: 0},
  {id: 22, category: "Clio", name: "Always willing to help, thrives as a team", rank: 0},
  {id: 23, category: "User Interaction", name: "Contributes to ‘hallway testing’ new flows / components.", rank: 0},
  {id: 24, category: "User Interaction", name: "Understands the iterative design process and is critical of user flow and design", rank: 0},
  {id: 25, category: "Testing Skills", name: "Solid understanding of most features in the Clio App.", rank: 0},
  {id: 26, category: "Testing Skills", name: "Primarily executes Manual tests, and some automated tests in areas I am familiar with.", rank: 0},
  {id: 27, category: "Testing Skills", name: "Follows process. Identifies areas that can be automated.", rank: 0},
  {id: 28, category: "Testing Skills", name: "Ensures critical and blocker bugs are not overlooked.", rank: 0},
  {id: 29, category: "Live a learning Mindset", name: "Share my knowledge with other employees and/or the development community", rank: 0},
  {id: 30, category: "Live a learning Mindset", name: "Create architectural reviews for problems", rank: 0},
  {id: 31, category: "Drawing the Fucking Owl Clio", name: "Represent Clio in the community - this can be meetups, community forum postings, open source projects, etc", rank: 0},
  {id: 32, category: "Technical", name: "Monitor my code once it is in production and be responsible for deployed bugs", rank: 0},
  {id: 33, category: "Stamps of Approval", name: "Serves/Advises Squads on requirements for 'QA-Sign Off'.", rank: 0},
  {id: 34, category: "Stamps of Approval", name: "Sign off on lower complexity test plans and testing.", rank: 0},
  {id: 35, category: "Stamps of Approval", name: "Sign off on small-sized or lower-complexity code reviews from areas of the code base I am familiar with", rank: 0},
  {id: 36, category: "Clio", name: "Live the Clio values", rank: 0},
  {id: 37, category: "User Interaction", name: "Builds components using Clio's style guidelines", rank: 0},
  {id: 38, category: "Live a learning Mindset", name: "Actively Mentor Others", rank: 0},
  {id: 39, category: "Live a learning Mindset", name: "Engage in any architectural review (0/5)", rank: 0},
  {id: 40, category: "Live a learning Mindset", name: "Learns from mistakes and shares lessons with the team. Rarely repeats any mistake. eg PostMortems, L&L, emails, documentation", rank: 0},
  {id: 41, category: "Live a learning Mindset", name: "Teaches and advises Squad(s) on best pratices. eg. blog posts, L&L etc", rank: 0},
  {id: 42, category: "Live a learning Mindset", name: "Seeks out and builds on feedback.", rank: 0},
  {id: 43, category: "Live a learning Mindset", name: "Actively engages in Product improvement reviews and discussions.", rank: 0},
  {id: 44, category: "Drawing the Fucking Owl", name: "Own medium projects and features to completion with guidance", rank: 0},
  {id: 45, category: "Drawing the Fucking Owl", name: "Actively helps Squads identify ways to reduce the number of bugs introduced and found during development.", rank: 0},
  {id: 46, category: "Drawing the Fucking Owl", name: "Ability to understand, debug and contribute to server side API implementations", rank: 0},
  {id: 47, category: "Technical", name: "Understanding of Computing Science Theory. (Algorithms, Best Practices, etc.) And, able to apply them in code.", rank: 0},
  {id: 48, category: "Technical", name: "write performant and low battery overhead code and ability to use profilers to diagnose performance and memory/battery usage problems", rank: 0},
  {id: 49, category: "Technical", name: "Audit libraries and frameworks before adding them to the code base", rank: 0},
  {id: 50, category: "Technical", name: "Write clearly written code", rank: 0},
  {id: 51, category: "Technical", name: "Be able to get up to speed in arbitrary areas of Clio's code base quickly", rank: 0},
  {id: 52, category: "Technical", name: "Identify, prioritize, and proactively tackle code debt", rank: 0},
  {id: 53, category: "Technical", name: "Be able to implement complex view hierarchies with understanding of each of Android’s view characteristics, and interactions with Activity/Fragment lifecycle", rank: 0},
  {id: 54, category: "Technical", name: "Thorough understanding of iOS's reference counting model of memory management", rank: 0},
  {id: 55, category: "Technical", name: "Strong understanding of HTTP protocol and general web development", rank: 0},
  {id: 56, category: "Technical", name: "Strong understanding of CSS / JS / HTML.", rank: 0},
  {id: 57, category: "Technical", name: "Solves Medium Complexity Automation Problems", rank: 0},
  {id: 58, category: "Technical", name: "Shares and teaches best practices for Automation", rank: 0},
  {id: 59, category: "Stamps of Approval", name: "Sign off on any small-sized or lower-complexity code reviews (0/10)", rank: 0},
  {id: 60, category: "Stamps of Approval", name: "Sign off on any medium-sized or medium complexity code reviews ", rank: 0},
  {id: 61, category: "Clio", name: "Understand the core parts of Clio", rank: 0},
  {id: 62, category: "Clio", name: "Recommend and contribute to QA process improvements in Product.", rank: 0},
  {id: 63, category: "User Interaction", name: "Understands Usability / UI pattern reuse / antipatterns and when they are appropriate or inappropriate to use", rank: 0},
  {id: 64, category: "User Interaction", name: "Engages in Design Reviews", rank: 0},
  {id: 65, category: "Testing Skills", name: "Can execute any required Manual and Automated tests.", rank: 0},
  {id: 66, category: "Testing Skills", name: "Write/Review/Follow test plan for QAs and Devs", rank: 0},
  {id: 67, category: "Testing Skills", name: "Identifies areas where Quality is deficient. Specifically, Customer facing quality issues. (ie. would generate a support call, but is not necessarily 'broken')", rank: 0},
  {id: 68, category: "Live a learning Mindset", name: "Aware of news and developments in our stack, how it affects our codebase / roadmap and shares this information with the group", rank: 0},
  {id: 69, category: "Drawing the Fucking Owl", name: "Own large projects and features to completion with guidance", rank: 0},
  {id: 70, category: "Drawing the Fucking Owl", name: "Own any emergency problem. (Eg. Data loss, user unable to perform critical actions)", rank: 0},
  {id: 71, category: "Drawing the Fucking Owl", name: "Work on hard problems alone", rank: 0},
  {id: 72, category: "Technical", name: "Knows when security problems exist in code and can offer solutions. (Works with internal security experts when needed)", rank: 0},
  {id: 73, category: "Technical", name: "Write code without fundamental algorithmic/architectural problems", rank: 0},
  {id: 74, category: "Technical", name: "Break a complex ticket (EPIC) into smaller tickets for rest of the team", rank: 0},
  {id: 75, category: "Stamps of Approval", name: "Sign off on large-sized or high-complexity code reviews from areas of the code base I am familiar with", rank: 0},
  {id: 76, category: "Clio", name: "Determine all required stakeholders of feature(s) during estimation", rank: 0},
  {id: 77, category: "Clio", name: "Estimate the amout of work required for a ticket in any areas of the code base ", rank: 0},
  {id: 78, category: "Clio", name: "Make hire/no-hire decisions in an interview as well as know how to apply a scoring rubric", rank: 0},
  {id: 79, category: "Live a learning Mindset", name: "Propose sensible solutions to almost any problem and can communicate options, pros and cons, and justifications", rank: 0},
  {id: 80, category: "Live a learning Mindset", name: "Propose learning initiatives to level up the team", rank: 0},
  {id: 81, category: "Live a learning Mindset", name: "Rigorously pursues and shares knowledge of the field", rank: 0},
  {id: 82, category: "Live a learning Mindset", name: "have thorough understanding of security vulnerability and consequences of mobile/web applications", rank: 0},
  {id: 83, category: "Live a learning Mindset", name: "in-depth knowledge of OS interactions (services, permissions, content provider etc)", rank: 0},
  {id: 84, category: "Drawing the Fucking Owl", name: "Own any project/feature to completion", rank: 0},
  {id: 85, category: "Technical", name: "Understand consequences of algorithmic or architectural decisions", rank: 0},
  {id: 86, category: "Technical", name: "Build scalable infrastructure that can support other features (eg. Permissioning, Syncing)", rank: 0},
  {id: 87, category: "Technical", name: "Primarily writes and supports Automated tests and infrastructure.", rank: 0},
  {id: 88, category: "Technical", name: "Writes scalable Automation tools, tests, and infrastructure", rank: 0},
  {id: 89, category: "Technical", name: "Solves hard and complex automation problems. Recommends and sees through technical decisions that impact Automation in Product.", rank: 0},
  {id: 90, category: "Stamps of Approval", name: "Sign off on any large-sized or high-complexity code reviews", rank: 0},
  {id: 91, category: "Stamps of Approval", name: "Sign off on any load/performance testing", rank: 0},
  {id: 92, category: "Stamps of Approval", name: "Sign off on any database migration", rank: 0},
  {id: 93, category: "Clio", name: "Regularly Advising which areas of CLio could be impacted by proposed feature development", rank: 0},
  {id: 94, category: "Clio", name: "Intimate QA and Clio App knowledge.", rank: 0},
  {id: 95, category: "Clio", name: "Understand the deploy process and can own this when required", rank: 0},
  {id: 96, category: "Clio", name: "Lead a technical interview. Developer and iterating on hiring projects and process", rank: 0},
  {id: 97, category: "Clio", name: "Guide and own process changes in Product", rank: 0},
  {id: 98, category: "Clio", name: "Strong understanding of the Android framework and how it relates to Clio's use", rank: 0},
  {id: 99, category: "Clio", name: "Responsible with snapshots of production data", rank: 0},
  {id: 100, category: "User Interaction", name: "Backup visual design choices with facts / theory / reason.", rank: 0},
  {id: 101, category: "User Interaction", name: "Understand basic UX and design concepts and collaborates on and vets design solutions", rank: 0},
  {id: 102, category: "Live a learning Mindset", name: "To be seen as technical mentor to every member of the team and always willing to help", rank: 0},
  {id: 103, category: "Drawing the Fucking Owl", name: "Advocate to leadership for important shifts roadmap priorities", rank: 0},
  {id: 104, category: "Drawing the Fucking Owl", name: "Debug the hardest problems the team encounters", rank: 0},
  {id: 105, category: "Technical", name: "Understand the implications that solutions will have on other levels of Clio's stack", rank: 0},
  {id: 106, category: "Technical", name: "Demonstrate subject matter expertise by being involved in projects related to the speciality", rank: 0},
  {id: 107, category: "Clio", name: "Demonstrate leadership abilities (eg via roles like squad coordinator, chapter leader, ministry head, etc)", rank: 0},
  {id: 108, category: "Live a learning Mindset", name: "Demonstrate interest in the specialty via self directed learning (read books, take courses, attend conferences, talk to subject matter experts)", rank: 0},
  {id: 109, category: "Live a learning Mindset", name: "Demonstrate the ability to present & teach concepts (eg via L&L, documentation, blog posts, etc)", rank: 0},
  {id: 110, category: "Technical", name: "Advocates the specialty in many or most architecture reviews", rank: 0}
])
CompetencyRole.create!([
  {id: 263, competency_id: 1, role_id: 1},
  {id: 264, competency_id: 2, role_id: 1},
  {id: 265, competency_id: 3, role_id: 1},
  {id: 266, competency_id: 4, role_id: 1},
  {id: 267, competency_id: 5, role_id: 2},
  {id: 268, competency_id: 5, role_id: 3},
  {id: 269, competency_id: 5, role_id: 4},
  {id: 270, competency_id: 5, role_id: 5},
  {id: 271, competency_id: 6, role_id: 2},
  {id: 272, competency_id: 6, role_id: 3},
  {id: 273, competency_id: 6, role_id: 4},
  {id: 274, competency_id: 6, role_id: 5},
  {id: 275, competency_id: 7, role_id: 2},
  {id: 276, competency_id: 7, role_id: 3},
  {id: 277, competency_id: 7, role_id: 4},
  {id: 278, competency_id: 7, role_id: 5},
  {id: 279, competency_id: 8, role_id: 1},
  {id: 280, competency_id: 8, role_id: 2},
  {id: 281, competency_id: 8, role_id: 3},
  {id: 282, competency_id: 8, role_id: 4},
  {id: 283, competency_id: 8, role_id: 5},
  {id: 284, competency_id: 9, role_id: 1},
  {id: 285, competency_id: 9, role_id: 2},
  {id: 286, competency_id: 9, role_id: 3},
  {id: 287, competency_id: 9, role_id: 4},
  {id: 288, competency_id: 9, role_id: 5},
  {id: 289, competency_id: 10, role_id: 1},
  {id: 290, competency_id: 10, role_id: 2},
  {id: 291, competency_id: 10, role_id: 3},
  {id: 292, competency_id: 10, role_id: 4},
  {id: 293, competency_id: 10, role_id: 5},
  {id: 294, competency_id: 11, role_id: 1},
  {id: 295, competency_id: 12, role_id: 2},
  {id: 296, competency_id: 12, role_id: 5},
  {id: 297, competency_id: 13, role_id: 4},
  {id: 298, competency_id: 14, role_id: 1},
  {id: 299, competency_id: 14, role_id: 2},
  {id: 300, competency_id: 14, role_id: 3},
  {id: 301, competency_id: 14, role_id: 4},
  {id: 302, competency_id: 14, role_id: 5},
  {id: 303, competency_id: 15, role_id: 1},
  {id: 304, competency_id: 15, role_id: 2},
  {id: 305, competency_id: 15, role_id: 3},
  {id: 306, competency_id: 15, role_id: 4},
  {id: 307, competency_id: 15, role_id: 5},
  {id: 308, competency_id: 16, role_id: 1},
  {id: 309, competency_id: 16, role_id: 2},
  {id: 310, competency_id: 16, role_id: 3},
  {id: 311, competency_id: 16, role_id: 4},
  {id: 312, competency_id: 16, role_id: 5},
  {id: 313, competency_id: 17, role_id: 3},
  {id: 314, competency_id: 18, role_id: 1},
  {id: 315, competency_id: 18, role_id: 2},
  {id: 316, competency_id: 18, role_id: 3},
  {id: 317, competency_id: 19, role_id: 5},
  {id: 318, competency_id: 20, role_id: 4},
  {id: 319, competency_id: 21, role_id: 2},
  {id: 320, competency_id: 21, role_id: 3},
  {id: 321, competency_id: 21, role_id: 4},
  {id: 322, competency_id: 21, role_id: 5},
  {id: 323, competency_id: 22, role_id: 1},
  {id: 324, competency_id: 22, role_id: 2},
  {id: 325, competency_id: 22, role_id: 3},
  {id: 326, competency_id: 22, role_id: 4},
  {id: 327, competency_id: 22, role_id: 5},
  {id: 328, competency_id: 23, role_id: 3},
  {id: 329, competency_id: 24, role_id: 3},
  {id: 330, competency_id: 25, role_id: 1},
  {id: 331, competency_id: 26, role_id: 1},
  {id: 332, competency_id: 27, role_id: 1},
  {id: 333, competency_id: 28, role_id: 1},
  {id: 334, competency_id: 29, role_id: 2},
  {id: 335, competency_id: 29, role_id: 3},
  {id: 336, competency_id: 29, role_id: 4},
  {id: 337, competency_id: 29, role_id: 5},
  {id: 338, competency_id: 30, role_id: 2},
  {id: 339, competency_id: 30, role_id: 3},
  {id: 340, competency_id: 30, role_id: 4},
  {id: 341, competency_id: 30, role_id: 5},
  {id: 342, competency_id: 31, role_id: 1},
  {id: 343, competency_id: 31, role_id: 2},
  {id: 344, competency_id: 31, role_id: 3},
  {id: 345, competency_id: 31, role_id: 4},
  {id: 346, competency_id: 31, role_id: 5},
  {id: 347, competency_id: 32, role_id: 2},
  {id: 348, competency_id: 32, role_id: 3},
  {id: 349, competency_id: 32, role_id: 4},
  {id: 350, competency_id: 32, role_id: 5},
  {id: 351, competency_id: 33, role_id: 1},
  {id: 352, competency_id: 34, role_id: 1},
  {id: 353, competency_id: 35, role_id: 2},
  {id: 354, competency_id: 35, role_id: 3},
  {id: 355, competency_id: 35, role_id: 4},
  {id: 356, competency_id: 35, role_id: 5},
  {id: 357, competency_id: 36, role_id: 1},
  {id: 358, competency_id: 36, role_id: 2},
  {id: 359, competency_id: 36, role_id: 3},
  {id: 360, competency_id: 36, role_id: 4},
  {id: 361, competency_id: 36, role_id: 5},
  {id: 362, competency_id: 37, role_id: 3},
  {id: 363, competency_id: 38, role_id: 1},
  {id: 364, competency_id: 38, role_id: 2},
  {id: 365, competency_id: 38, role_id: 3},
  {id: 366, competency_id: 38, role_id: 4},
  {id: 367, competency_id: 38, role_id: 5},
  {id: 368, competency_id: 39, role_id: 2},
  {id: 369, competency_id: 39, role_id: 3},
  {id: 370, competency_id: 39, role_id: 4},
  {id: 371, competency_id: 39, role_id: 5},
  {id: 372, competency_id: 40, role_id: 1},
  {id: 373, competency_id: 40, role_id: 2},
  {id: 374, competency_id: 40, role_id: 3},
  {id: 375, competency_id: 40, role_id: 4},
  {id: 376, competency_id: 40, role_id: 5},
  {id: 377, competency_id: 41, role_id: 1},
  {id: 378, competency_id: 41, role_id: 2},
  {id: 379, competency_id: 41, role_id: 3},
  {id: 380, competency_id: 41, role_id: 4},
  {id: 381, competency_id: 41, role_id: 5},
  {id: 382, competency_id: 42, role_id: 1},
  {id: 383, competency_id: 42, role_id: 2},
  {id: 384, competency_id: 42, role_id: 3},
  {id: 385, competency_id: 42, role_id: 4},
  {id: 386, competency_id: 42, role_id: 5},
  {id: 387, competency_id: 43, role_id: 1},
  {id: 388, competency_id: 43, role_id: 2},
  {id: 389, competency_id: 43, role_id: 3},
  {id: 390, competency_id: 43, role_id: 4},
  {id: 391, competency_id: 43, role_id: 5},
  {id: 392, competency_id: 44, role_id: 1},
  {id: 393, competency_id: 44, role_id: 2},
  {id: 394, competency_id: 44, role_id: 3},
  {id: 395, competency_id: 44, role_id: 4},
  {id: 396, competency_id: 44, role_id: 5},
  {id: 397, competency_id: 45, role_id: 1},
  {id: 398, competency_id: 46, role_id: 2},
  {id: 399, competency_id: 46, role_id: 3},
  {id: 400, competency_id: 46, role_id: 4},
  {id: 401, competency_id: 46, role_id: 5},
  {id: 402, competency_id: 47, role_id: 2},
  {id: 403, competency_id: 47, role_id: 3},
  {id: 404, competency_id: 47, role_id: 4},
  {id: 405, competency_id: 47, role_id: 5},
  {id: 406, competency_id: 48, role_id: 5},
  {id: 407, competency_id: 49, role_id: 2},
  {id: 408, competency_id: 49, role_id: 3},
  {id: 409, competency_id: 49, role_id: 4},
  {id: 410, competency_id: 49, role_id: 5},
  {id: 411, competency_id: 50, role_id: 1},
  {id: 412, competency_id: 50, role_id: 2},
  {id: 413, competency_id: 50, role_id: 3},
  {id: 414, competency_id: 50, role_id: 4},
  {id: 415, competency_id: 50, role_id: 5},
  {id: 416, competency_id: 51, role_id: 2},
  {id: 417, competency_id: 51, role_id: 3},
  {id: 418, competency_id: 51, role_id: 4},
  {id: 419, competency_id: 51, role_id: 5},
  {id: 420, competency_id: 52, role_id: 2},
  {id: 421, competency_id: 52, role_id: 3},
  {id: 422, competency_id: 52, role_id: 4},
  {id: 423, competency_id: 52, role_id: 5},
  {id: 424, competency_id: 53, role_id: 5},
  {id: 425, competency_id: 54, role_id: 4},
  {id: 426, competency_id: 55, role_id: 1},
  {id: 427, competency_id: 55, role_id: 2},
  {id: 428, competency_id: 55, role_id: 3},
  {id: 429, competency_id: 55, role_id: 4},
  {id: 430, competency_id: 55, role_id: 5},
  {id: 431, competency_id: 56, role_id: 3},
  {id: 432, competency_id: 57, role_id: 1},
  {id: 433, competency_id: 58, role_id: 1},
  {id: 434, competency_id: 59, role_id: 2},
  {id: 435, competency_id: 59, role_id: 3},
  {id: 436, competency_id: 59, role_id: 4},
  {id: 437, competency_id: 59, role_id: 5},
  {id: 438, competency_id: 60, role_id: 1},
  {id: 439, competency_id: 60, role_id: 2},
  {id: 440, competency_id: 60, role_id: 3},
  {id: 441, competency_id: 60, role_id: 4},
  {id: 442, competency_id: 60, role_id: 5},
  {id: 443, competency_id: 61, role_id: 1},
  {id: 444, competency_id: 61, role_id: 2},
  {id: 445, competency_id: 61, role_id: 3},
  {id: 446, competency_id: 61, role_id: 4},
  {id: 447, competency_id: 61, role_id: 5},
  {id: 448, competency_id: 62, role_id: 1},
  {id: 449, competency_id: 63, role_id: 3},
  {id: 450, competency_id: 64, role_id: 3},
  {id: 451, competency_id: 65, role_id: 1},
  {id: 452, competency_id: 66, role_id: 1},
  {id: 453, competency_id: 67, role_id: 1},
  {id: 454, competency_id: 68, role_id: 2},
  {id: 455, competency_id: 68, role_id: 3},
  {id: 456, competency_id: 68, role_id: 4},
  {id: 457, competency_id: 68, role_id: 5},
  {id: 458, competency_id: 69, role_id: 1},
  {id: 459, competency_id: 69, role_id: 2},
  {id: 460, competency_id: 69, role_id: 3},
  {id: 461, competency_id: 69, role_id: 4},
  {id: 462, competency_id: 69, role_id: 5},
  {id: 463, competency_id: 70, role_id: 2},
  {id: 464, competency_id: 70, role_id: 3},
  {id: 465, competency_id: 70, role_id: 4},
  {id: 466, competency_id: 70, role_id: 5},
  {id: 467, competency_id: 71, role_id: 1},
  {id: 468, competency_id: 71, role_id: 2},
  {id: 469, competency_id: 71, role_id: 3},
  {id: 470, competency_id: 71, role_id: 4},
  {id: 471, competency_id: 71, role_id: 5},
  {id: 472, competency_id: 72, role_id: 2},
  {id: 473, competency_id: 72, role_id: 3},
  {id: 474, competency_id: 72, role_id: 4},
  {id: 475, competency_id: 72, role_id: 5},
  {id: 476, competency_id: 73, role_id: 1},
  {id: 477, competency_id: 73, role_id: 2},
  {id: 478, competency_id: 73, role_id: 3},
  {id: 479, competency_id: 73, role_id: 4},
  {id: 480, competency_id: 73, role_id: 5},
  {id: 481, competency_id: 74, role_id: 2},
  {id: 482, competency_id: 74, role_id: 3},
  {id: 483, competency_id: 74, role_id: 4},
  {id: 484, competency_id: 74, role_id: 5},
  {id: 485, competency_id: 75, role_id: 2},
  {id: 486, competency_id: 75, role_id: 3},
  {id: 487, competency_id: 75, role_id: 4},
  {id: 488, competency_id: 75, role_id: 5},
  {id: 489, competency_id: 76, role_id: 2},
  {id: 490, competency_id: 76, role_id: 3},
  {id: 491, competency_id: 76, role_id: 4},
  {id: 492, competency_id: 76, role_id: 5},
  {id: 493, competency_id: 77, role_id: 2},
  {id: 494, competency_id: 77, role_id: 3},
  {id: 495, competency_id: 77, role_id: 4},
  {id: 496, competency_id: 77, role_id: 5},
  {id: 497, competency_id: 78, role_id: 2},
  {id: 498, competency_id: 78, role_id: 3},
  {id: 499, competency_id: 78, role_id: 4},
  {id: 500, competency_id: 78, role_id: 5},
  {id: 501, competency_id: 79, role_id: 2},
  {id: 502, competency_id: 79, role_id: 3},
  {id: 503, competency_id: 79, role_id: 4},
  {id: 504, competency_id: 79, role_id: 5},
  {id: 505, competency_id: 80, role_id: 1},
  {id: 506, competency_id: 80, role_id: 2},
  {id: 507, competency_id: 80, role_id: 3},
  {id: 508, competency_id: 80, role_id: 4},
  {id: 509, competency_id: 80, role_id: 5},
  {id: 510, competency_id: 81, role_id: 1},
  {id: 511, competency_id: 81, role_id: 2},
  {id: 512, competency_id: 81, role_id: 3},
  {id: 513, competency_id: 81, role_id: 4},
  {id: 514, competency_id: 81, role_id: 5},
  {id: 515, competency_id: 82, role_id: 2},
  {id: 516, competency_id: 82, role_id: 3},
  {id: 517, competency_id: 82, role_id: 4},
  {id: 518, competency_id: 82, role_id: 5},
  {id: 519, competency_id: 83, role_id: 4},
  {id: 520, competency_id: 83, role_id: 5},
  {id: 521, competency_id: 84, role_id: 1},
  {id: 522, competency_id: 84, role_id: 2},
  {id: 523, competency_id: 84, role_id: 3},
  {id: 524, competency_id: 84, role_id: 4},
  {id: 525, competency_id: 84, role_id: 5},
  {id: 526, competency_id: 85, role_id: 2},
  {id: 527, competency_id: 85, role_id: 3},
  {id: 528, competency_id: 85, role_id: 4},
  {id: 529, competency_id: 85, role_id: 5},
  {id: 530, competency_id: 86, role_id: 2},
  {id: 531, competency_id: 86, role_id: 3},
  {id: 532, competency_id: 86, role_id: 4},
  {id: 533, competency_id: 86, role_id: 5},
  {id: 534, competency_id: 87, role_id: 1},
  {id: 535, competency_id: 88, role_id: 1},
  {id: 536, competency_id: 89, role_id: 1},
  {id: 537, competency_id: 90, role_id: 1},
  {id: 538, competency_id: 90, role_id: 2},
  {id: 539, competency_id: 90, role_id: 3},
  {id: 540, competency_id: 90, role_id: 4},
  {id: 541, competency_id: 90, role_id: 5},
  {id: 542, competency_id: 91, role_id: 1},
  {id: 543, competency_id: 91, role_id: 2},
  {id: 544, competency_id: 92, role_id: 2},
  {id: 545, competency_id: 92, role_id: 5},
  {id: 546, competency_id: 93, role_id: 2},
  {id: 547, competency_id: 93, role_id: 3},
  {id: 548, competency_id: 93, role_id: 4},
  {id: 549, competency_id: 93, role_id: 5},
  {id: 550, competency_id: 94, role_id: 1},
  {id: 551, competency_id: 95, role_id: 2},
  {id: 552, competency_id: 95, role_id: 3},
  {id: 553, competency_id: 95, role_id: 4},
  {id: 554, competency_id: 95, role_id: 5},
  {id: 555, competency_id: 96, role_id: 2},
  {id: 556, competency_id: 96, role_id: 3},
  {id: 557, competency_id: 96, role_id: 4},
  {id: 558, competency_id: 96, role_id: 5},
  {id: 559, competency_id: 97, role_id: 2},
  {id: 560, competency_id: 97, role_id: 3},
  {id: 561, competency_id: 97, role_id: 4},
  {id: 562, competency_id: 97, role_id: 5},
  {id: 563, competency_id: 98, role_id: 5},
  {id: 564, competency_id: 99, role_id: 2},
  {id: 565, competency_id: 99, role_id: 4},
  {id: 566, competency_id: 99, role_id: 5},
  {id: 567, competency_id: 100, role_id: 3},
  {id: 568, competency_id: 101, role_id: 3},
  {id: 569, competency_id: 102, role_id: 1},
  {id: 570, competency_id: 102, role_id: 2},
  {id: 571, competency_id: 102, role_id: 3},
  {id: 572, competency_id: 102, role_id: 4},
  {id: 573, competency_id: 102, role_id: 5},
  {id: 574, competency_id: 103, role_id: 1},
  {id: 575, competency_id: 103, role_id: 2},
  {id: 576, competency_id: 103, role_id: 3},
  {id: 577, competency_id: 103, role_id: 4},
  {id: 578, competency_id: 103, role_id: 5},
  {id: 579, competency_id: 104, role_id: 1},
  {id: 580, competency_id: 104, role_id: 2},
  {id: 581, competency_id: 104, role_id: 3},
  {id: 582, competency_id: 104, role_id: 4},
  {id: 583, competency_id: 104, role_id: 5},
  {id: 584, competency_id: 105, role_id: 2},
  {id: 585, competency_id: 105, role_id: 3},
  {id: 586, competency_id: 105, role_id: 4},
  {id: 587, competency_id: 105, role_id: 5},
  {id: 588, competency_id: 106, role_id: 6},
  {id: 589, competency_id: 107, role_id: 6},
  {id: 590, competency_id: 108, role_id: 6},
  {id: 591, competency_id: 109, role_id: 6},
  {id: 592, competency_id: 110, role_id: 6}
])
Department.create!([
  {id: 1, name: "Founders"},
  {id: 2, name: "Sales"},
  {id: 6, name: "Customer Support"},
  {id: 8, name: "Marketing"},
  {id: 9, name: "Finance"},
  {id: 11, name: "Business Development"},
  {id: 13, name: "SDR Team"},
  {id: 16, name: "POps"},
  {id: 18, name: "Special Projects"},
  {id: 19, name: "Product"},
  {id: 20, name: "Data Operations"},
  {id: 22, name: "Customer Success"}
])
Role.create!([
  {id: 1, department_id: 19, name: "QA"},
  {id: 2, department_id: 19, name: "Web - Backend"},
  {id: 3, department_id: 19, name: "Web - Frontend"},
  {id: 4, department_id: 19, name: "iOS"},
  {id: 5, department_id: 19, name: "Android"},
  {id: 6, department_id: 19, name: "Specialist"}
])
UserRole.create!([
  {id: 1, user_id: 176, role_id: 1},
  {id: 2, user_id: 68, role_id: 2},
  {id: 3, user_id: 141, role_id: 3},
  {id: 4, user_id: 87, role_id: 4},
  {id: 5, user_id: 55, role_id: 5}
])
