Department.create!([
  {id: 1, name: "Founders"},
  {id: 22, name: "Customer Success"},
  {id: 6, name: "Customer Support"},
  {id: 16, name: "POps"},
  {id: 2, name: "Sales"},
  {id: 19, name: "Product"},
  {id: 20, name: "Data Operations"},
  {id: 8, name: "Marketing"},
  {id: 18, name: "Special Projects"},
  {id: 9, name: "Finance"},
  {id: 11, name: "Business Development"},
  {id: 13, name: "SDR Team"}
])

User.create!([
  {id: 4, email: "jack.newton@clio.com", full_name: "Jack Newton", title: "CEO and Founder", manager_id: nil, department_id: 1},
  {id: 5, email: "rian.gauvreau@clio.com", full_name: "Rian Gauvreau", title: "COO and Founder", manager_id: 4, department_id: 1},
  {id: 7, email: "kazia.biernacki@clio.com", full_name: "Kazia Formosa", title: "Switch Specialist", manager_id: 247, department_id: 22},
  {id: 9, email: "kimberly.davison@clio.com", full_name: "Kimberly Davison", title: "Switch Specialist", manager_id: 15, department_id: 22},
  {id: 10, email: "catherine.hillier@clio.com", full_name: "Catherine Hillier", title: "Director of Customer Support", manager_id: 5, department_id: 6},
  {id: 15, email: "jason.pinch@clio.com", full_name: "Jason Pinch", title: "Migrations Manager", manager_id: 247, department_id: 22},
  {id: 16, email: "angus.wong@clio.com", full_name: "Angus Wong", title: "IT Coordinator", manager_id: 5, department_id: 16},
  {id: 19, email: "oliver.browes@clio.com", full_name: "Oliver Browes", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 22, email: "tyler.goodwin@goclio.com", full_name: "Tyler Goodwin", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 33, email: "derek.rawlings@clio.com", full_name: "Derek Rawlings", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 36, email: "joshua.tanzola@clio.com", full_name: "Joshua Tanzola", title: "Director of Sales Engineering", manager_id: 113, department_id: 2},
  {id: 38, email: "dan.woods@clio.com", full_name: "Daniel Woods", title: "Regional Sales Director", manager_id: 113, department_id: 2},
  {id: 39, email: "tonia.chambers@clio.com", full_name: "Antonia Newton", title: "Office Manager", manager_id: 5, department_id: 16},
  {id: 40, email: "remi.broemeling@clio.com", full_name: "Remi Broemeling", title: "System Administrator", manager_id: 4, department_id: 19},
  {id: 42, email: "naoya.makino@clio.com", full_name: "Naoya Makino", title: "Lead Developer - Android", manager_id: 180, department_id: 19},
  {id: 43, email: "fraser.newton@clio.com", full_name: "Fraser Newton", title: "Lead Scientist", manager_id: 46, department_id: 20},
  {id: 44, email: "chris.thompson@clio.com", full_name: "Chris Thompson", title: "Security Lead", manager_id: 45, department_id: 19},
  {id: 45, email: "tys.von.gaza@clio.com", full_name: "Tys von Gaza", title: "Director of Product Development", manager_id: 4, department_id: 19},
  {id: 46, email: "george.psiharis@clio.com", full_name: "George Psiharis", title: "Vice President, Business Development & Partnerships", manager_id: 4, department_id: 20},
  {id: 49, email: "jo.goodrich@clio.com", full_name: "Jo Goodrich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 55, email: "kieran.elliott@clio.com", full_name: "Kieran Elliott", title: "Sr. Software Developer", manager_id: 87, department_id: 19},
  {id: 68, email: "kyle.doliveira@clio.com", full_name: "Kyle d'Oliveira", title: "Software Architecture Specialist", manager_id: 45, department_id: 19},
  {id: 69, email: "geoff.thierman@clio.com", full_name: "Geoffrey Thierman", title: "Sr UI Designer", manager_id: 264, department_id: 19},
  {id: 75, email: "shirley.ho@clio.com", full_name: "Shirley Ho", title: "Sr UI Designer", manager_id: 264, department_id: 19},
  {id: 77, email: "lyndsi.nolan@clio.com", full_name: "Lyndsi Nolan", title: "Customer Support Specialist", manager_id: 10, department_id: 6},
  {id: 78, email: "zachary.pope@clio.com", full_name: "Zachary Pope", title: "Technical Escalations Manager", manager_id: 10, department_id: 6},
  {id: 79, email: "joshua.lenon@clio.com", full_name: "Joshua Lenon", title: "Lawyer in Residence", manager_id: 205, department_id: 8},
  {id: 83, email: "kevin.needham@clio.com", full_name: "Kevin Needham", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 84, email: "eugene.or@clio.com", full_name: "Eugene Or", title: "UI Designer", manager_id: 264, department_id: 19},
  {id: 85, email: "lauren.sanders@clio.com", full_name: "Lauren Sanders", title: "Special Projects Coordinator & Executive Assistant", manager_id: 4, department_id: 18},
  {id: 87, email: "jason.peebles@clio.com", full_name: "Jason Peebles", title: "Lead Developer - iOS", manager_id: 45, department_id: 19},
  {id: 89, email: "dennis.taylor@clio.com", full_name: "Dennis Taylor", title: "Performance Specialist", manager_id: 45, department_id: 19},
  {id: 94, email: "jodelene.weir@clio.com", full_name: "Jodelene Weir", title: "Event Producer", manager_id: 46, department_id: 8},
  {id: 95, email: "craig.carlyle@clio.com", full_name: "Craig Carlyle", title: "UI Designer", manager_id: 141, department_id: 19},
  {id: 97, email: "kyle.demeule@clio.com", full_name: "Kyle Demeule", title: "Data Scientist", manager_id: 43, department_id: 20},
  {id: 101, email: "arthur.chui@clio.com", full_name: "Arthur Chui", title: "Senior Software Developer", manager_id: 45, department_id: 19},
  {id: 102, email: "derek.bolen@clio.com", full_name: "Derek Bolen", title: "Social Media & Community Coordinator", manager_id: 127, department_id: 8},
  {id: 104, email: "tanyia.mackenzie@clio.com", full_name: "Tanyia MacKenzie", title: "Office Administrator", manager_id: 39, department_id: 16},
  {id: 107, email: "reilly.forshaw@clio.com", full_name: "Reilly Forshaw", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 109, email: "dana.stasyk@clio.com", full_name: "Dana Stasyk", title: "Customer Support Coordinator", manager_id: 130, department_id: 6},
  {id: 113, email: "steven.silberbach@clio.com", full_name: "Steven Silberbach", title: "Vice President, Global Sales", manager_id: 4, department_id: 2},
  {id: 114, email: "drew.goddyn@clio.com", full_name: "Drew Goddyn", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 115, email: "matthew.horne@goclio.com", full_name: "Matt Horne", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 116, email: "pouyan.bibalan@clio.com", full_name: "Pouyan Taghipour Bibalan", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 117, email: "jeremy.papp@clio.com", full_name: "Jeremy Papp", title: "Product Team Project Manager", manager_id: 45, department_id: 19},
  {id: 121, email: "rory.fitzpatrick@clio.com", full_name: "Rory Fitzpatrick", title: "Customer Success Coordinator", manager_id: 166, department_id: 22},
  {id: 123, email: "navneet.gill@clio.com", full_name: "Navneet Gill", title: "Data Operations Analyst", manager_id: 46, department_id: 20},
  {id: 124, email: "adrian.pape@clio.com", full_name: "Adrian Pape", title: "Controller", manager_id: 172, department_id: 9},
  {id: 125, email: "halley.strecko@clio.com", full_name: "Halley Strecko", title: "Customer Success Associate", manager_id: 247, department_id: 22},
  {id: 126, email: "christopher.yeh@clio.com", full_name: "Christopher Yeh", title: "Manager of Talent Development", manager_id: 5, department_id: 16},
  {id: 127, email: "preet.minhas@clio.com", full_name: "Preet Minhas", title: "Director of Inbound Marketing and Operations", manager_id: 4, department_id: 8},
  {id: 129, email: "brendan.devereux@clio.com", full_name: "Brendan Devereux", title: "Switch Specialist", manager_id: 15, department_id: 22},
  {id: 130, email: "david.perry@clio.com", full_name: "David Perry", title: "Customer Support Manager", manager_id: 10, department_id: 6},
  {id: 131, email: "jon.tastemel@clio.com", full_name: "Jon Tastemel", title: "Web Developer", manager_id: 127, department_id: 8},
  {id: 132, email: "elsa.brink@clio.com", full_name: "Elsa Brink", title: "Senior Demand Generation Marketing Manager", manager_id: 4, department_id: 8},
  {id: 133, email: "lynn.gagne@clio.com", full_name: "Lynn Gagne", title: "Customer Success Trainer", manager_id: 247, department_id: 22},
  {id: 134, email: "chelsea.kelch@clio.com", full_name: "Chelsea Kelch", title: "Customer Success Coordinator", manager_id: 247, department_id: 22},
  {id: 135, email: "catherine.mclachlan@clio.com", full_name: "Catherine McLachlan", title: "Designer", manager_id: 136, department_id: 8},
  {id: 136, email: "jiaan.co@clio.com", full_name: "Jiaan Co", title: "Visual Designer", manager_id: 127, department_id: 8},
  {id: 137, email: "daniela.szary@clio.com", full_name: "Daniela Szary", title: "Event Planner", manager_id: 4, department_id: 8},
  {id: 138, email: "kyle.harrison@clio.com", full_name: "Kyle Harrison", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 139, email: "jeremy.secker@clio.com", full_name: "Jeremy Secker", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 141, email: "terry.white@clio.com", full_name: "Terry White", title: "Software Developer", manager_id: 45, department_id: 19},
  {id: 142, email: "muriel.teague@clio.com", full_name: "Muriel Teague", title: "Customer Success Trainer", manager_id: 130, department_id: 22},
  {id: 143, email: "adam.stanton@clio.com", full_name: "Adam Stanton", title: "System Administrator", manager_id: 40, department_id: 19},
  {id: 144, email: "ryan.sydor@clio.com", full_name: "Ryan Sydor", title: "Regional Sales Director", manager_id: 113, department_id: 2},
  {id: 145, email: "jordan.suen@clio.com", full_name: "Jordan Suen", title: "Senior Accountant", manager_id: 124, department_id: 9},
  {id: 147, email: "colin.mcmahon@clio.com", full_name: "Colin McMahon", title: "Training Specialist", manager_id: 10, department_id: 6},
  {id: 152, email: "yuki.hamade@clio.com", full_name: "Yuki Hamade", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 153, email: "john.oconnor@clio.com", full_name: "John O'Connor", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 154, email: "melanie.watson@clio.com", full_name: "Melanie Watson", title: "Senior Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 156, email: "hamad.mirza@clio.com", full_name: "Hamad Mirza", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 157, email: "maggie.nyunt@clio.com", full_name: "Margaret Peckham-Nyunt", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 160, email: "carina.hunt@clio.com", full_name: "Carina Dielissen Hunt", title: "Training Specialist (New Releases)", manager_id: 10, department_id: 6},
  {id: 163, email: "marc.barlo@clio.com", full_name: "Marc Barlo", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 164, email: "kaitlin.graves@clio.com", full_name: "Kaitlin Graves", title: "Office Administrator", manager_id: 39, department_id: 16},
  {id: 165, email: "leslie.sto.tomas@clio.com", full_name: "Leslie Sto. tomas", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 166, email: "derek.fitzpatrick@clio.com", full_name: "Derek Fitzpatrick", title: "General Manager, EMEA", manager_id: 46, department_id: 11},
  {id: 167, email: "saad.ahmed@clio.com", full_name: "Saad Ahmed", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 169, email: "brittany.holmes@clio.com", full_name: "Brittany Holmes", title: "Switch Specialist", manager_id: 247, department_id: 22},
  {id: 170, email: "mark.rainey@clio.com", full_name: "Mark Rainey", title: "Customer Support Coordinator", manager_id: 130, department_id: 6},
  {id: 171, email: "sean.healy@clio.com", full_name: "Sean Healy", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 172, email: "robert.froment@clio.com", full_name: "Rob Froment", title: "Chief Financial Officer", manager_id: 4, department_id: 9},
  {id: 173, email: "sherry.shao@clio.com", full_name: "Sherry Shao", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 176, email: "richard.chong@clio.com", full_name: "Richard Chong", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 179, email: "prashant.jacob@clio.com", full_name: "Prashant Jacob", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 180, email: "jordan.raine@clio.com", full_name: "Jordan Raine", title: "Software Developer", manager_id: 45, department_id: 19},
  {id: 181, email: "michael.cheung@clio.com", full_name: "Michael Cheung", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 183, email: "nicholas.paufler@clio.com", full_name: "Nicholas Paufler", title: "System Administrator", manager_id: 40, department_id: 19},
  {id: 188, email: "brittney.lloyd@clio.com", full_name: "Brittney Lloyd", title: "Business Development Administrator", manager_id: 195, department_id: 11},
  {id: 189, email: "walt.nathaniel@clio.com", full_name: "Walt Nathaniel", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 190, email: "dylan.runkel@clio.com", full_name: "Dylan Runkel", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 191, email: "michelle.fryzuk@clio.com", full_name: "Michelle Fryzuk", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 192, email: "brian.oreilly@clio.com", full_name: "Brian O'Reilly", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 193, email: "pavel.dusatko@clio.com", full_name: "Pavel Dusatko", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 194, email: "luke.wagner@clio.com", full_name: "Luke Wagner", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 195, email: "andrew.gay@clio.com", full_name: "Andrew Gay", title: "Manager of Strategic Partnerships", manager_id: 46, department_id: 11},
  {id: 199, email: "matthew.faust@clio.com", full_name: "Matthew Faust", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 201, email: "michael.wei@clio.com", full_name: "Mike Wei", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 202, email: "audrey.gagnon@clio.com", full_name: "Audrey Gagnon", title: "Account Executive", manager_id: 38, department_id: 2},
  {id: 203, email: "eric.bin@clio.com", full_name: "Eric Bin", title: "Lead Product Manager", manager_id: 4, department_id: 19},
  {id: 204, email: "aaron.cheng@clio.com", full_name: "Aaron Cheng", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 205, email: "beth.kszan@clio.com", full_name: "Beth Kszan", title: "Director, Product Marketing", manager_id: 4, department_id: 8},
  {id: 206, email: "taryn.friederich@clio.com", full_name: "Taryn Friederich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 207, email: "tyler.nelson@clio.com", full_name: "Tyler Nelson", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 208, email: "andrea.stevenson@clio.com", full_name: "Andrea Stevenson", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 209, email: "jef.curtis@clio.com", full_name: "Jef Curtis", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 210, email: "ilana.shulman@clio.com", full_name: "Ilana Shulman", title: "Director of Business Development", manager_id: 113, department_id: 2},
  {id: 211, email: "tami.runyon@clio.com", full_name: "Tami Runyon", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 212, email: "jane.lee@clio.com", full_name: "Jane Lee", title: "Talent Acquisition Specialist", manager_id: 126, department_id: 16},
  {id: 213, email: "darren.wilson@clio.com", full_name: "Darren Wilson", title: "Copywriter", manager_id: 127, department_id: 8},
  {id: 214, email: "erick.costigan@clio.com", full_name: "Erick Costigan", title: "Quality Assurance Analyst", manager_id: 291, department_id: 19},
  {id: 215, email: "erik.auvinen@clio.com", full_name: "Erik Auvinen", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 216, email: "alex.kim@clio.com", full_name: "Alex Kim", title: "Talent Acquisition Specialist", manager_id: 126, department_id: 16},
  {id: 217, email: "waylon.mcgill@clio.com", full_name: "Waylon McGill", title: "Manager, Sales Development", manager_id: 113, department_id: 2},
  {id: 218, email: "josh.lecker@clio.com", full_name: "Josh Lecker", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 222, email: "marcus.stein@clio.com", full_name: "Marcus Stein", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 223, email: "ashique.khan@clio.com", full_name: "Ashique Khan", title: "Manager, Sales Operations", manager_id: 46, department_id: 20},
  {id: 224, email: "guillermo.tellez@clio.com", full_name: "Guillermo Tellez", title: "Senior Product Manager", manager_id: 203, department_id: 19},
  {id: 226, email: "amy.berkowitz@clio.com", full_name: "Amy Berkowitz", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 228, email: "wade.fraser@clio.com", full_name: "Wade Fraser", title: "Senior Business Development Representative", manager_id: 210, department_id: 2},
  {id: 229, email: "georgina.marcus@clio.com", full_name: "Georgina Marcus", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 231, email: "matthew.patterson@clio.com", full_name: "Matthew Patterson", title: "Senior Business Development Representative", manager_id: 210, department_id: 2},
  {id: 233, email: "mark.reich@clio.com", full_name: "Mark Reich", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 234, email: "emmanuel.akena@clio.com", full_name: "Emmanuel Akena", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 235, email: "michelle.lodge@clio.com", full_name: "Michelle Lodge", title: "Payroll & Benefits Coordinator", manager_id: 124, department_id: 9},
  {id: 237, email: "steven.harbaruk@clio.com", full_name: "Steven Harbaruk", title: "Intern, Product Management", manager_id: 203, department_id: 19},
  {id: 239, email: "paul.holden@clio.com", full_name: "Paul Holden", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 240, email: "fiona.finn@clio.com", full_name: "Fiona Finn", title: "Marketing Specialist", manager_id: 205, department_id: 8},
  {id: 243, email: "roshini.sakhrani@clio.com", full_name: "Roshini Sakhrani", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 244, email: "jeff.marvin@clio.com", full_name: "Jeff Marvin", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 245, email: "dwight.tomalty@clio.com", full_name: "Dwight Tomalty", title: "Software Developer", manager_id: 141, department_id: 19},
  {id: 246, email: "charles.ferguson@clio.com", full_name: "Charles Ferguson", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 247, email: "michael.chou@clio.com", full_name: "Michael Chou", title: "Customer Success Manager", manager_id: 5, department_id: 22},
  {id: 248, email: "jason.cho@clio.com", full_name: "Jason Cho", title: "Quality Assurance Analyst ", manager_id: 291, department_id: 19},
  {id: 249, email: "ryan.akerboom@clio.com", full_name: "Ryan Akerboom", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 251, email: "Nathaniel.Mots@clio.com", full_name: "Nathaniel Mots", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 253, email: "rebecca.mcmanus@clio.com", full_name: "Rebecca McManus", title: "Sales Development Rep", manager_id: 166, department_id: 13},
  {id: 254, email: "ross.weldon@clio.com", full_name: "Ross Weldon", title: "Marketing Specialist", manager_id: 166, department_id: 8},
  {id: 255, email: "aiza.corcuera@clio.com", full_name: "Aiza Corcuera", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 256, email: "ruman.kang@clio.com", full_name: "Ruman Kang", title: "Content Marketing Specialist", manager_id: 127, department_id: 8},
  {id: 257, email: "jeffrey.huang@clio.com", full_name: "Jeffrey Huang", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 258, email: "james.goertzen@clio.com", full_name: "James Goertzen", title: "Technical Escalations Agent", manager_id: 78, department_id: 6},
  {id: 259, email: "adam.dewji@clio.com", full_name: "Adam Dewji", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 260, email: "jonathan.ho@clio.com", full_name: "Jonathan Ho", title: "Marketing Operations Specialist", manager_id: 127, department_id: 8},
  {id: 261, email: "rehan.nayyer@clio.com", full_name: "Rehan Nayyer", title: "Salesforce Developer", manager_id: 46, department_id: 20},
  {id: 263, email: "alexander.kardash@clio.com", full_name: "Alexander Kardash", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 264, email: "ernie.bin@clio.com", full_name: "Ernie Bin", title: "Director, User Experience", manager_id: 4, department_id: 19},
  {id: 265, email: "joash.carey@clio.com", full_name: "Joash Carey", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 266, email: "robyn.dobson@clio.com", full_name: "Robyn Dobson", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 267, email: "madison.goddyn@clio.com", full_name: "Madison Goddyn", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 269, email: "cale.shapera@clio.com", full_name: "Cale Shapera", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 270, email: "mengxi.liao@clio.com", full_name: "Mengxi Liao", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 271, email: "jack.chao@clio.com", full_name: "Jack Chao", title: "Sales Development Rep", manager_id: 217, department_id: 2},
  {id: 272, email: "david.le.corre@clio.com", full_name: "David Le Corre", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 273, email: "scott.hamilton@clio.com", full_name: "Scott Hamilton", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 275, email: "jeremy.noonan@clio.com", full_name: "Jeremy Noonan", title: "IT Administrator", manager_id: 5, department_id: 16},
  {id: 276, email: "jeff.perrin@clio.com", full_name: "Jeff Perrin", title: "Software Developer", manager_id: 101, department_id: 19},
  {id: 277, email: "mark.hazlett@clio.com", full_name: "Mark Hazlett", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 278, email: "kenneth.calcitas@clio.com", full_name: "Kenneth Calcitas", title: "Digital Media Portfolio Specialist", manager_id: 132, department_id: 8},
  {id: 279, email: "irina.belova@clio.com", full_name: "Irina Belova", title: "Senior Product Designer", manager_id: 264, department_id: 19},
  {id: 281, email: "shawky.hanana@clio.com", full_name: "Shawky Hanana", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 282, email: "calvin.cestari@clio.com", full_name: "Calvin Cestari", title: "Software Developer", manager_id: 87, department_id: 19},
  {id: 283, email: "jessie.mok@clio.com", full_name: "Jessie Mok", title: nil, manager_id: 124, department_id: 9},
  {id: 284, email: "euphemia.wong@clio.com", full_name: "Euphemia Wong", title: "UX Designer", manager_id: 264, department_id: 19},
  {id: 285, email: "steve.thompson@clio.com", full_name: "Steve Thompson", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 286, email: "michael.brewer@clio.com", full_name: "Michael Brewer", title: "Account Executive", manager_id: 144, department_id: 2},
  {id: 287, email: "nelson.wang@clio.com", full_name: "Nelson Wang", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 288, email: "shaheer.shabbir@clio.com", full_name: "Shaheer Shabbir", title: "Software Developer", manager_id: 68, department_id: 19},
  {id: 289, email: "irmantas.levanas@clio.com", full_name: "Irmantas Levanas", title: "Account Executive", manager_id: 166, department_id: 2},
  {id: 290, email: "matthew.griffeth@clio.com", full_name: "Matthew Griffeth", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 291, email: "james.coles-nash@clio.com", full_name: "James Coles-Nash", title: "QA Automation Lead", manager_id: 45, department_id: 19},
  {id: 292, email: "jacob.bosancich@clio.com", full_name: "Jacob Bosancich", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 293, email: "samantha.sterzai@clio.com", full_name: "Samantha Sterzai", title: "Business Development Representative", manager_id: 210, department_id: 2},
  {id: 295, email: "pawan.kumar.adda@clio.com", full_name: "Pawan Kumar Adda", title: "Product Manager", manager_id: 203, department_id: 19},
  {id: 296, email: "agnes.carissa.utomo@clio.com", full_name: "Agnes Utomo", title: "Software Developer, Co-op", manager_id: 101, department_id: 19},
  {id: 297, email: "landon.trybuch@clio.com", full_name: "Landon Trybuch", title: "Software Developer, Co-op", manager_id: 101, department_id: 19},
  {id: 298, email: "karina.simard@clio.com", full_name: "Karina Simard", title: "Software Developer", manager_id: 180, department_id: 19},
  {id: 299, email: "andrew.booth@clio.com", full_name: "Andrew Booth", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 300, email: "niamh.monahan@clio.com", full_name: "Niamh Monahan", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 301, email: "katrina.guyduy@clio.com", full_name: "Katrina Guyduy", title: "Web Developer", manager_id: 131, department_id: 8},
  {id: 302, email: "nicole.manalac@clio.com", full_name: "Nicole Manalac", title: "Talent Generalist", manager_id: 126, department_id: 16},
  {id: 303, email: "lydia.choi@clio.com", full_name: "Lydia Choi", title: "Customer Support Specialist", manager_id: 130, department_id: 6},
  {id: 304, email: "allison.mcgerrigle@clio.com", full_name: "Allison McGerrigle", title: "Talent Generalist", manager_id: 126, department_id: 16}
])

Role.create!([
  { id: 1, department_id: 19, name: "QA" },
  { id: 2, department_id: 19, name: "Web - Backend" },
  { id: 3, department_id: 19, name: "Web - Frontend" },
  { id: 4, department_id: 19, name: "iOS" },
  { id: 5, department_id: 19, name: "Android" },
])

RolesUsers.create([

])
